### ISSUE TITLE
Delete master branch?

### ISSUE THREAD

**Issue by lyzidiamond** [codeforamerica/lexington-qold#65]
@eeeschwartz what do you think?

**Comment by eeeschwartz** [comment]
makes sense. Then we can recreate it off of dev and treat it like a true master type situation branch

**Comment by lyzidiamond** [comment]
@eeeschwartz would you be willing to do this? I'm not sure I have enough confidence in my git skillz.

**Comment by eeeschwartz** [comment]
I set master to dev and got rid of dev. We can work off of master now.

**Comment by lyzidiamond** [comment]
:+1: :sunflower: :walking:
