### ISSUE TITLE
Enable IE9

### ISSUE THREAD

**Issue by lyzidiamond** [codeforamerica/lexington-qold#66]
I did some browser testing! Here's what I found out:
- IE7: doesn't work, has a banner that tells you it's not going to work
- IE8: doesn't work, has a banner that tells you it's not going to work
- IE9: loads, but then crashes and reloads a bunch
  **\- IE10 and IE11: works, but slider doesn't stop, even when you press the pause button**
- Firefox and Chrome work for every version except Firefox 3 and 3.6.

Let's look into the slider stuff and the IE9 situation. @eeeschwartz @livienyin

**Comment by eeeschwartz** [comment]
We should pick this up again to fix the IE9 issues before launch

**Comment by lyzidiamond** [comment]
agree! :+1: :penguin: :lollipop:
